export const dataCountries = [
  { code: 'ar', label: 'Argentina' },
  { code: 'au', label: 'Australia' },
  { code: 'us', label: 'United States Of America' },
  { code: 'br', label: 'Brazil' },
  { code: 'bo', label: 'Bolivia' },
  { code: 'ca', label: 'Canada' },
  { code: 'at', label: 'Austria' },
  { code: 'cl', label: 'Chile' },
  { code: 'cn', label: 'China' },
  { code: 'es', label: 'España' },
  { code: 'ua', label: 'Ukraine' },
  { code: 'co', label: 'Colombia' },
  { code: 'hr', label: 'Croatia' },
  { code: 'ec', label: 'Ecuador' },
  { code: 'fr', label: 'France' },
  { code: 'de', label: 'Germany' },
  { code: 'hn', label: 'Honduras' },
  { code: 'in', label: 'India' },
  { code: 'ir', label: 'Iran' },
  { code: 'it', label: 'Italy' },
  { code: 'jp', label: 'Japan' },
  { code: 'mx', label: 'Mexico' },
  { code: 'kr', label: 'Korea' },
  { code: 'pe', label: 'Peru' },
  { code: 'pt', label: 'Portugal' },
  { code: 'uy', label: 'Uruguay' },
];
